### ISSUE TITLE
Internal and external server crash. Why?

### ISSUE THREAD

**Issue by Kevadroz** [superckl/BiomeTweaker#104]
Server (internal and external) crash on world load, but i can't find the reason on logs and on my scripts.
My scripts: [Scripts.zip](https://github.com/superckl/BiomeTweaker/files/750780/Scripts.zip)
Some log (crash report doesn't creates):

[...]
[15:39:12] [Server thread/TRACE] [BiomeTweaker/BiomeTweaker]: Sending event FMLLoadCompleteEvent to mod BiomeTweaker
[15:39:12] [Server thread/INFO] [SuperScript/BiomeTweaker]: Found 149 tweaks to apply for stage FINISHED_LOAD. Applying...
[15:39:12] [Server thread/WARN] [BiomeTweaker/BiomeTweaker]: Attempted to set property color but corresponding property was not found for biomes. Value: "3e3e00"
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@7c4c213e
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@7ceca604
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@6c81427b
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@11cfaca1
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@48188f2b
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@7b32de96
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@3de92701
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@6194c484
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@9e7d2d
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@30ce5267
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandAddDictionaryType@6b355ff9
[15:39:12] [Server thread/WARN] [BiomeTweaker/BiomeTweaker]: Attempted to set property color but corresponding property was not found for biomes. Value: "3e3e00"
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@73d5af8
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@3310504c
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@10f9a0be
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@57218ef3
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@18e71d8
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@2d746744
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@7dbe0607
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@4c73f3d2
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@2be2b8a0
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@25a6c063
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandAddDictionaryType@35127ddf
[15:39:12] [Server thread/WARN] [BiomeTweaker/BiomeTweaker]: Attempted to set property color but corresponding property was not found for biomes. Value: "3e3e00"
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@46ca018c
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@10071022
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@56ba96fc
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@1d6794b7
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@edb16de
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@522debbf
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@2b0b5ba6
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@1551cfd6
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@1f443b4a
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@496a44c8
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandAddDictionaryType@581d528
[15:39:12] [Server thread/WARN] [BiomeTweaker/BiomeTweaker]: Attempted to set property color but corresponding property was not found for biomes. Value: "3e3e00"
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@e73aa78
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@47b97989
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@37f44245
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@3ee83804
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@37a6e217
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@718e09c0
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@78b70834
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@3ea8c081
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@9b3e9a2
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@68c3915
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandAddDictionaryType@7475890c
[15:39:12] [Server thread/WARN] [BiomeTweaker/BiomeTweaker]: Attempted to set property color but corresponding property was not found for biomes. Value: "003e00"
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@21255739
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@1c2fcb66
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@b692394
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@147d0b16
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@27c4d455
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@710ecc46
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@c118352
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@3c80138d
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@5821c98
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@5e0c6a05
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandAddDictionaryType@6983751
[15:39:12] [Server thread/WARN] [BiomeTweaker/BiomeTweaker]: Attempted to set property color but corresponding property was not found for biomes. Value: "3e0000"
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@4c26092
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@6fd57465
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@43e7e95e
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@7809e9e0
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@66215fc7
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@332b416b
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@42b344a8
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@7804ecea
[15:39:12] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@92d8c1b
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@299ef352
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandAddDictionaryType@53868eb
[15:39:13] [Server thread/WARN] [BiomeTweaker/BiomeTweaker]: Attempted to set property color but corresponding property was not found for biomes. Value: "3e3e00"
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@3cb19542
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@19167691
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@149a7b52
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@188e531b
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@749b2daa
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@1c2ad6fe
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty@66b9d8b0
[15:39:13] [Server thread/ERROR] [SuperScript/BiomeTweaker]: Failed to execute script command: me.superckl.biometweaker.script.command.ScriptCommandAddRemoveBiome@313a483d
[15:39:13] [Server thread/DEBUG] [FML/BiomeTweaker]: Bar Step: BiomeTweaker Initialization - Applying scripts took 1.886s
[15:39:13] [Server thread/INFO] [BiomeTweaker/BiomeTweaker]: Generating biome status report...
[15:39:13] [Server thread/TRACE] [BiomeTweaker/BiomeTweaker]: Sent event FMLLoadCompleteEvent to mod BiomeTweaker
[15:39:13] [Server thread/DEBUG] [FML/]: Bar Step: LoadComplete - BiomeTweaker took 1.896s
[...]
[15:39:15] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from AVAILABLE to SERVER_ABOUT_TO_START. Loading cannot continue
[15:39:15] [Server thread/ERROR] [FML/]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAA	ivtoolkit{1.2.8.5} [IvToolkit] (minecraft.jar) 
	UCHIJAA	forgecreeperheal{2.0.1} [Forge Creeper Heal 2.0.1] ([1.10.2]ForgeCreeperHeal-2.0.1.jar) 
	UCHIJAA	aether_legacy{v1.0-1.9.4} [Aether Legacy] (aether_legacy-1.2.jar) 
	UCHIJAA	AppleCore{2.1.0} [AppleCore] (AppleCore-mc1.10.2-2.1.0.jar) 
	UCHIJAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAA	thedragonlib{1.10.2-1.0.3.0} [TheDragonLib] (thedragonlib-1.10.2-1.0.3.0.jar) 
	UCHIJAA	armorplus{1.10.2-8.3.0.1} [ArmorPlus] (armorplus-1.10.2-8.3.0.1.jar) 
	UCHIJAA	ArrowFix{1.1} [Tipped Arrow Fixer] (ArrowFix-1.1.jar) 
	UCHIJAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJEE	BiomeTweaker{2.1.230} [BiomeTweaker] (BiomeTweaker-1.10.2-2.1.230.jar) 
	UCHIJAA	blockarmor{2.1} [Block Armor] (BlockArmor-1.10.2-2.1.jar) 
	UCHIJAA	coroai{v1.1.9} [coroai] (coroutil-1.10.2-1.1.9.jar) 
	UCHIJAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.9.jar) 
	UCHIJAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.9.jar) 
	UCHIJAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(20nov16).jar) 
	UCHIJAA	dsurround{3.2.1.1} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.2.1.1.jar) 
	UCHIJAA	epicsiegemod{11.0.152} [Epic Siege Mod] (EpicSiegeMod-11.0.152.jar) 
	UCHIJAA	event_tweaks{1.1.1} [event_tweaks] (Event Tweaks 1.1.1.jar) 
	UCHIJAA	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.10-1.10.2.jar) 
	UCHIJAA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCHIJAA	increasemobs{1.0.1} [IncreaseMobs] (IncreaseMobs_1.9.4-v1.0.1.jar) 
	UCHIJAA	nex{1.0.0b} [NetherEx] (NetherEx_1.10.2-1.0.0b.jar) 
	UCHIJAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAA	offlineskins{1.10.2-v2a} [OfflineSkins] (OfflineSkins-1.10.2-v2a.jar) 
	UCHIJAA	primal{0.2.18} [PrimalCore] (PrimalCore-0.2.18.jar) 
	UCHIJAA	realdrops{1.0.7} [Realistic Item Drops] (RealisticItemDrops-1.0.7.jar) 
	UCHIJAA	reccomplex{1.1.1} [Recurrent Complex] (RecurrentComplex-1.1.1.jar) 
	UCHIJAA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.8.1-1.10.2.jar) 
	UCHIJAA	SilentLib{1.1.0} [Silent Lib] (SilentLib-1.10.2-1.1.0-23.jar) 
	UCHIJAA	scalinghealth{1.0.1} [Scaling Health] (ScalingHealth-1.10.2-1.0.1-32.jar) 
	UCHIJAA	SimpleDimensions{1.3} [Simple Dimensions] (SimpleDimensions-MC1.10-1.3.jar) 
	UCHIJAA	simulatednights{1.11-1.0.0} [Simulated Nights] (simulatednights-1.11-1.0.0.jar) 
	UCHIJAA	SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.6.jar) 
	UCHIJAA	tombmanygraves{1.10.2-2.1.11} [Tomb Many Graves] (TombManyGraves-1.10.2-2.1.11.jar) 
	UCHIJAA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCHIJAA	undergroundbiomes{1.0.0} [Underground Biomes] (UndergroundBiomesConstructs-1.10-0.9-beta.4.jar) 
	UCHIJAA	weather2{v2.3.15} [Localized Weather & Storms] (weather2-1.10.2-2.3.15.jar) 
	UCHIJAA	examplemod{1.0} [Example Mod] (WTF-Expedition_1.10.2_1.2.jar) 
	UCHIJAA	wtfcore{1.10.2_v1.1} [wtfcore] (WTF-Expedition_1.10.2_1.2.jar) 
	UCHIJAA	zombieawareness{v1.20} [Zombie Awareness] (zombieawareness-1.10.2-1.20.jar) 
	UD	BiomeTweakerCore{2.1.230} [BiomeTweaker Core] (minecraft.jar) 
[15:39:15] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[15:39:15] [Server thread/ERROR] [FML/]: Caught exception from BiomeTweaker (BiomeTweaker)
java.lang.NullPointerException
	at me.superckl.biometweaker.util.BiomeHelper.fillJsonObject(BiomeHelper.java:96) ~[BiomeHelper.class:?]
	at me.superckl.biometweaker.BiomeTweaker.generateOutputFiles(BiomeTweaker.java:229) ~[BiomeTweaker.class:?]
	at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:216) ~[BiomeTweaker.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:803) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[15:39:15] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BiomeTweaker (BiomeTweaker)

Caused by: java.lang.NullPointerException
	at me.superckl.biometweaker.util.BiomeHelper.fillJsonObject(BiomeHelper.java:96) ~[BiomeHelper.class:?]
	at me.superckl.biometweaker.BiomeTweaker.generateOutputFiles(BiomeTweaker.java:229) ~[BiomeTweaker.class:?]
	at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:216) ~[BiomeTweaker.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:803) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[15:39:17] [Server thread/DEBUG] [FML/]: Reverting to frozen data state.
[...]
[15:39:22] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[15:39:22] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by superckl** [comment]
What version of BiomeTweaker are you running?

**Comment by Kevadroz** [comment]
I am running version 2.1.230

**Comment by superckl** [comment]
Please confirm that the issue still persists while running the latest experimental 1.10.2 version:

http://jenkins.superckl.me/job/BiomeTweaker%201.10/

**Comment by Kevadroz** [comment]
It still crash with the same error. Are my scripts bad coded?

**Comment by superckl** [comment]
Don't put your numbers in quotes, only the name of field. Do `6543` versus `"6543"`

**Comment by Kevadroz** [comment]
yes, thats the cause of the problem, now i am trying to solve something similar in my scripts. (I thinked that the quotes were needed in any "setPropertyOfBiome" command, but i realized that and tried to solve it, i did it, partially).

**Comment by Cronosus** [comment]
i have similar crash, even i dont use any own scripts

**Comment by superckl** [comment]
Closing this since it's 1.10.2. Please verify it still is an issue on 1.11.2 and let me know.
