### ISSUE TITLE
Hang on world load with 1.11.2-3.0.281

### ISSUE THREAD

**Issue by brisingraerowing** [superckl/BiomeTweaker#119]
From game output:

```[15:24:45] [Server thread/FATAL] [FML]: The following problems were captured during this phase
[15:24:45] [Server thread/ERROR] [FML]: Caught exception from biometweaker (java.lang.UnsupportedOperationException: JsonNull)
[15:24:45] [Server thread/WARN] [FML]: =============================================================
[15:24:45] [Server thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[15:24:45] [Server thread/WARN] [FML]: Offender: org/multimc/EntryPoint.main([Ljava/lang/String;)V
[15:24:45] [Server thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[15:24:45] [Server thread/WARN] [FML]: =============================================================
[15:24:45] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BiomeTweaker (biometweaker)

Caused by: java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsString(JsonElement.java:191) ~[JsonElement.class:?]
	at me.superckl.biometweaker.BiomeTweaker.generateOutputFiles(BiomeTweaker.java:330) ~[BiomeTweaker.class:?]
	at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:212) ~[BiomeTweaker.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647) ~[forge-1.11.2-13.20.1.2393-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:836) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521) ~[bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352) ~[bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[1.11.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) ~[OneSixLauncher.class:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) ~[OneSixLauncher.class:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) ~[EntryPoint.class:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) ~[EntryPoint.class:?]
```

Only Script:

```
biomeWastelands = forBiomes(90)

biomeWastelands.registerGenBiomeRep(2)
```

(Replaces the BOP Wastelands with Vanilla Desert)

**Comment by superckl** [comment]
Please verify the latest build has fixed the issue. I think I identified it, but it's hard to tell without a full client log.

http://jenkins.superckl.me/job/BiomeTweaker%201.11/294/

**Comment by brisingraerowing** [comment]
I'm testing now. Hopefully this works. I'll get a full client log if it hangs again.

**Comment by brisingraerowing** [comment]
It appears to have worked! The world loaded perfectly fine. Thanks!
