### ISSUE TITLE
Trying to change the sky color

### ISSUE THREAD

**Issue by Winddbourne** [superckl/BiomeTweaker#121]
I'm having an issue trying to change the skycolor in biometweaker for 1.10.2. I've tracked down the problem in the game logs but I'm not sure how to solve it. 

Mod BiomeTweakerCore has been disabled through configuration
Failed to find meaning in command set(“skycolor”,0). It will be ignored.

It happens in that exact order. Looking at the wiki it seems there is supposed to be a configuration file somewhere . . . but I can't find it. Honestly I'm half thinking it hasn't generated because the mod has never run. 

But I'm hoping that I'm missing something obvious. 

Biometweakercore is also listed for this error but I don't know if it's related to the problem:

2017-08-10 01:17:33,694 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream 2017-08-10 01:17:33,697 WARN Caught Exception while in Loader.getResource. This may be innocuous. java.lang.IllegalArgumentException: name 	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:494) 	at sun.misc.URLClassPath.findResource(URLClassPath.java:176) 	at java.net.URLClassLoader$2.run(URLClassLoader.java:557) 	at java.net.URLClassLoader$2.run(URLClassLoader.java:555) 	at java.security.AccessController.doPrivileged(Native Method) 	at java.net.URLClassLoader.findResource(URLClassLoader.java:554) 	at java.lang.ClassLoader.getResource(ClassLoader.java:1093) 	at org.apache.logging.log4j.core.helpers.Loader.getResource(Loader.java:98) 	at org.apache.logging.log4j.core.config.ConfigurationFactory.getInputFromResource(ConfigurationFactory.java:300) 	at org.apache.logging.log4j.core.config.ConfigurationFactory.getInputFromString(ConfigurationFactory.java:280) 	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:380) 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:377) 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:149) 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:85) 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:34) 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:387) 	at me.superckl.biometweaker.core.ModBiomeTweakerCore.<clinit>(ModBiomeTweakerCore.java:14) 	at me.superckl.biometweaker.core.BiomeTweakerCallHook.call(BiomeTweakerCallHook.java:24) 	at me.superckl.biometweaker.core.BiomeTweakerCallHook.call(BiomeTweakerCallHook.java:20) 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:166) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)  2017-08-10 01:17:33,718 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="BiomeTweakerCore" timestamp="1502342253731" level="INFO" thread="main">     <log4j:Message><![CDATA[Beginning early config parsing...]]></log4j:Message>   </log4j:Event>
--

**Comment by superckl** [comment]
I think you have a very rare issue with quotation marks. The line you've pasted uses a niche version of quotation marks (open and close) that aren't recognized:
```Failed to find meaning in command set(“skycolor”,0). It will be ignored.```

Notice the quotation marks. You have `“` (open) and `”` (close) as opposed to only `"`. Please verify that you are not using the incorrect quotation marks in your scripts. If you are, either copy the correct quotation marks you see here, or use a different text editor that doesn't do that.

**Comment by Winddbourne** [comment]
That did make a difference and I'll remember to make sure not to have open and close quotes from now on. 
It is accepting skycolor but it is now giving a different problem:

Attempted to set property skycolor but corresponding property was not found for biomes. Value: 3355443

Darkness.set("skycolor", 3355443)

It also gave the same error for 0 (black) and 17 (Dark Gray) before I copied your example from the wiki directly into my code to see if I was just missing something. Any idea what's going on?

**Comment by superckl** [comment]
If I recall correctly, the property system in 1.10.2 is case sensetive. Try "skyColor".

**Comment by Winddbourne** [comment]
That did the trick and I wanted to come back and say thank you for the
help; and also to give you a big thumbs up on some of the new commands I
see in the wiki. I can now put decorations where I want, spawn biomes in
other dimensions! Both of these are huge for me and I really appreciate you
adding them. Have a great day. :)
