### ISSUE TITLE
registerGenBiomeRep Crashes.

### ISSUE THREAD

**Issue by Wissi** [superckl/BiomeTweaker#149]
Minecraft 1.12.2
Forge 14.23.0.2529
BiomeTweaker 1.12.1- 3.1.306

Script:

```# Vanilla Biomes

vanillaOcean = forBiomes(0)
vanillaDesert = forBiomes(2)
vanillaDesertHills = forBiomes(17)
vanillaDeepOcean = forBiomes(24)

# Replace Ocean biomes in generation

vanillaOcean.registerGenBiomeRep(2)
vanillaDeepOcean.registerGenBiomeRep(17)
```

Crash Log Header/Stacktrace:

```Description: Exception initializing level

java.lang.ArrayIndexOutOfBoundsException: 24
	at me.superckl.biometweaker.common.world.gen.layer.GenLayerReplacement.bakeMap(GenLayerReplacement.java:46)
	at me.superckl.biometweaker.common.world.gen.layer.GenLayerReplacement.func_75904_a(GenLayerReplacement.java:27)
	at net.minecraft.world.biome.BiomeProvider.func_180630_a(BiomeProvider.java:187)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:926)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:865)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:123)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at me.superckl.biometweaker.common.world.gen.layer.GenLayerReplacement.bakeMap(GenLayerReplacement.java:46)
	at me.superckl.biometweaker.common.world.gen.layer.GenLayerReplacement.func_75904_a(GenLayerReplacement.java:27)
	at net.minecraft.world.biome.BiomeProvider.func_180630_a(BiomeProvider.java:187)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:926)
```
Full crash log:
https://gist.github.com/Wissi/cad8ef74cc9b111e7b8461bdec9fbb69

**Comment by superckl** [comment]
This issue has already been fixed in the latest development builds.

http://jenkins.superckl.me/job/BiomeTweaker%201.12/

**Comment by Wissi** [comment]
Thank you very much.
