### ISSUE TITLE
Unable to find field waterColor in class net.minecraft.world.biome.Biome

### ISSUE THREAD

**Issue by Bobb-E-Burns** [superckl/BiomeTweaker#161]
`Forge: 14.23.1.2559`
`BiomeTweakerCore-1.12.2-1.0.22` 
`BiomeTweaker-1.12.2-3.1.322` from Jenkins
`Traverse-1.12.1-1.3.1`
Traverse is a biome mod which is mostly based on vanilla data.  

? Related issues: #154, #159 

Happens in both `BIOME_REGISTRY` & `POST_INIT`

Log:
```
[13:09:30] [main/ERROR] [SuperScript]: Failed to execute script command: me.superckl.biometweaker.script.command.misc.ScriptCommandSetBiomeProperty@16e63bf3
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: java.lang.IllegalStateException: Unable to find field waterColor in class net.minecraft.world.biome.Biome
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at me.superckl.api.biometweaker.property.PropertyField.verifyField(PropertyField.java:56)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at me.superckl.api.biometweaker.property.PropertyField.set(PropertyField.java:24)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at me.superckl.api.biometweaker.property.PropertyHelper.typeSafeSet(PropertyHelper.java:34)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at me.superckl.api.biometweaker.property.PropertyHelper.setProperty(PropertyHelper.java:27)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at me.superckl.biometweaker.script.command.misc.ScriptCommandSetBiomeProperty.perform(ScriptCommandSetBiomeProperty.java:42)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at me.superckl.api.superscript.script.command.BasicScriptCommandManager.applyCommandsFor(BasicScriptCommandManager.java:50)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at me.superckl.biometweaker.BiomeTweaker.onPostInit(BiomeTweaker.java:206)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:724)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[13:09:30] [main/INFO] [STDERR]: [me.superckl.api.superscript.script.command.BasicScriptCommandManager:applyCommandsFor:53]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

My script:
```
Tweaker.setScriptStage("BIOME_REGISTRY")
Tweaker.createBiome("Ominous_Woods", "traverse:woodlands")
Ominous_Woods = forBiomes("biometweaker:Ominous_Woods")
Ominous_Woods.set("name", "Ominous Woods")
Ominous_Woods.removeDicTypes("PLAINS")
Ominous_Woods.addDicTypes("FOREST")

Tweaker.setScriptStage("POST_INIT")
Ominous_Woods = forBiomes("biometweaker:Ominous_Woods")
Ominous_Woods.set("isSpawnBiome", true)
Ominous_Woods.set("genWeight", 1000)
Ominous_Woods.set("fillerBlock", "minecraft:glass")
Ominous_Woods.set("foliageColor", 6506163)
Ominous_Woods.set("grassColor", 6506163)
Ominous_Woods.set("waterColor", 6506163)
Ominous_Woods.set("waterTint", 6506163)
Ominous_Woods.set("skyColor", 6506163)
```

**Comment by superckl** [comment]
Did you enable the feature in BiomeTweakerCore?

**Comment by Bobb-E-Burns** [comment]
Yes, I've set everything (except Late Block Assignments) to true in `BiomeTweakerCore.cfg`

**Comment by Bobb-E-Burns** [comment]
The same error appears when I comment out waterColor and waterTint from my script and disable waterColor support in BTCore.

**Comment by superckl** [comment]
Can you provide a full log file?

**Comment by superckl** [comment]
Fixed in the latest commit. `waterTint` is a leftover property that shouldn't be settable anymore. I've removed it, so now `waterColor` is the only property relating to water color.
