### ISSUE TITLE
IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by Bobb-E-Burns** [superckl/BiomeTweaker#166]
`BiomeTweaker-1.12.2-3.1.332`

Using `newClusterDecoration` causes this error which results in the cluster placement failing.

```
leavesCluster = newClusterDecoration()
leavesCluster.set("mainBlock", "minecraft:leaves")
leavesCluster.set("count", 20)
leavesCluster.set("radius", 12)
leavesCluster.set("height", 4)
leavesCluster.addSoilBlock("minecraft:grass")
```

```
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at java.util.Random.nextInt(Random.java:388)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at me.superckl.biometweaker.common.world.gen.feature.WorldGenGenericTree.func_180709_b(WorldGenGenericTree.java:52)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at me.superckl.biometweaker.common.world.gen.feature.WorldGenTreesWrapper.generate(WorldGenTreesWrapper.java:22)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at me.superckl.biometweaker.common.world.gen.Decorator.runDecoration(Decorator.java:26)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at me.superckl.biometweaker.common.handler.BiomeEventHandler.onPostPopulateBiome(BiomeEventHandler.java:77)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_BiomeEventHandler_onPostPopulateBiome_Post.invoke(.dynamic)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:683)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:491)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1015)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:996)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[23:44:44] [Server thread/INFO] [STDERR]: [me.superckl.biometweaker.common.world.gen.Decorator:runDecoration:29]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by superckl** [comment]
That error is occurring due to a non-positive height variation in a tree decoration, not a cluster decoration. Can you provide your tree decorations?

**Comment by Bobb-E-Burns** [comment]
I was in a custome biome where I don't use any newTreeDecoration at the moment.
Let me disable the other biome.cfg and I'll try agian.

These are the two tree setups I used for my other test Biome.

```
lushDesertFoliage.set("minHeight", 2)
lushDesertFoliage.set("heightVariation", 1)
---
lushDesertFoliageShort.set("minHeight", 1)
lushDesertFoliageShort.set("heightVariation", 0) <-- This not okay?
```

**Comment by superckl** [comment]
Fixed. heighVaration for normal trees is always positive, so the methods weren't designed to handle 0.

**Comment by Bobb-E-Burns** [comment]
Next time I'll see an error I'll read more into the log to see what's causing it.  I don't know any Java but this error obviously says `GenericTree` and here I am assuming a cluster is causing it lol.
