### ISSUE TITLE
Unable to register a new biome.

### ISSUE THREAD

**Issue by C0LiSii0N** [superckl/BiomeTweaker#185]
Ok so, I try to register a new biome but nothing seems to work.. I removed all my script to keep just the one that register my biome and still nothing, I also tried with the config from the issue #107 but still crashing..
For the script I tried setStage and setScriptStage but nothing changed
My script:
```
Tweaker.setStage("BIOME_REGISTRY")
Tweaker.createBiome("larch_forest", "minecraft:forest")
larch = forBiomes("biometweaker:larch_forest")
larch.set("name", "Larch Forest")
larch.addToGeneration("WARM", 1000)
larch.addToGeneration("COOL", 1000)
```

My biome file(LarchForest (biometweaker_larch_forest).json):
```
{
  "ID": 40,
  "Name": "Larch Forest",
  "Resource Location": "biometweaker:larch_forest",
  "Class": "net.minecraft.world.biome.BiomeForest",
  "Root Height": 0.1,
  "Height Variation": 0.2,
  "Top Block": "minecraft:grass[snowy\u003dfalse]",
  "Filler Block": "minecraft:dirt[snowy\u003dfalse,variant\u003ddirt]",
  "Ocean Top Block": "Disabled. Activate in BiomeTweakerCore.",
  "Ocean Filler Block": "Disabled. Activate in BiomeTweakerCore.",
  "Actual Filler Blocks": "Disabled. Activate in BiomeTweakerCore.",
  "Grass Color": "Disabled. Activate in BiomeTweakerCore.",
  "Foliage Color": "Disabled. Activate in BiomeTweakerCore.",
  "Water Color": "16777215",
  "Temperature": 0.6,
  "Humidity": 0.6,
  "Water Tint": 16777215,
  "Enable Rain": true,
  "Enable Snow": false,
  "Dictionary Types": [
    "FOREST",
    "LARCH_TREES"
  ],
  "BiomeManager Entries": {
    "WARM Weights": [
      1000
    ],
    "COOL Weights": [
      1000
    ]
  },
  "Spawnable Creatures": [
    {
      "Entity Class": "net.minecraft.entity.passive.EntitySheep",
      "Weight": 12,
      "Min Group Count": 4,
      "Max Group Count": 4
    },
    {
      "Entity Class": "net.minecraft.entity.passive.EntityPig",
      "Weight": 10,
      "Min Group Count": 4,
      "Max Group Count": 4
    },
    {
      "Entity Class": "net.minecraft.entity.passive.EntityChicken",
      "Weight": 10,
      "Min Group Count": 4,
      "Max Group Count": 4
    },
    {
      "Entity Class": "net.minecraft.entity.passive.EntityCow",
      "Weight": 8,
      "Min Group Count": 4,
      "Max Group Count": 4
    }
  ],
  "Spawnable Monsters": [
    {
      "Entity Class": "net.minecraft.entity.monster.EntitySpider",
      "Weight": 100,
      "Min Group Count": 4,
      "Max Group Count": 4
    },
    {
      "Entity Class": "net.minecraft.entity.monster.EntityZombie",
      "Weight": 95,
      "Min Group Count": 4,
      "Max Group Count": 4
    },
    {
      "Entity Class": "net.minecraft.entity.monster.EntityZombieVillager",
      "Weight": 5,
      "Min Group Count": 1,
      "Max Group Count": 1
    },
    {
      "Entity Class": "net.minecraft.entity.monster.EntitySkeleton",
      "Weight": 100,
      "Min Group Count": 4,
      "Max Group Count": 4
    },
    {
      "Entity Class": "net.minecraft.entity.monster.EntityCreeper",
      "Weight": 100,
      "Min Group Count": 4,
      "Max Group Count": 4
    },
    {
      "Entity Class": "net.minecraft.entity.monster.EntitySlime",
      "Weight": 100,
      "Min Group Count": 4,
      "Max Group Count": 4
    },
    {
      "Entity Class": "net.minecraft.entity.monster.EntityEnderman",
      "Weight": 10,
      "Min Group Count": 1,
      "Max Group Count": 4
    },
    {
      "Entity Class": "net.minecraft.entity.monster.EntityWitch",
      "Weight": 5,
      "Min Group Count": 1,
      "Max Group Count": 1
    },
    {
      "Entity Class": "vazkii.quark.world.entity.EntityDweller",
      "Weight": 10,
      "Min Group Count": 1,
      "Max Group Count": 2
    },
    {
      "Entity Class": "vazkii.quark.world.entity.EntityAshen",
      "Weight": 10,
      "Min Group Count": 1,
      "Max Group Count": 2
    }
  ],
  "Spawnable Water Creatures": [
    {
      "Entity Class": "net.minecraft.entity.passive.EntitySquid",
      "Weight": 10,
      "Min Group Count": 4,
      "Max Group Count": 4
    }
  ],
  "Spawnable Cave Creatures": [
    {
      "Entity Class": "net.minecraft.entity.passive.EntityBat",
      "Weight": 10,
      "Min Group Count": 8,
      "Max Group Count": 8
    }
  ],
  "Spawn Biome": false,
  "Tweaked": true
}
```

The crash report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 18-04-20 21:18
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at me.superckl.biometweaker.script.command.generation.ScriptCommandCreateBiome.perform(ScriptCommandCreateBiome.java:118)
	at me.superckl.api.superscript.script.command.BasicScriptCommandManager.applyCommandsFor(BasicScriptCommandManager.java:50)
	at me.superckl.biometweaker.common.handler.RegistryEventHandler.onBiomeRegistry(RegistryEventHandler.java:17)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_RegistryEventHandler_onBiomeRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 666947752 bytes (636 MB) / 899678208 bytes (858 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4G -XX:MaxPermSize=256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2666 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID               | Version      | Source                          | Signature                                |
	|:----- |:---------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| UCH   | minecraft        | 1.12.2       | minecraft.jar                   | None                                     |
	| UCH   | mcp              | 9.42         | minecraft.jar                   | None                                     |
	| UCH   | FML              | 8.0.99.99    | my.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge            | 14.23.3.2666 | my.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | biometweakercore | 1.0.39       | minecraft.jar                   | None                                     |
	| UCH   | biometweaker     | 3.2.345      | BiomeTweaker-1.12.2-3.2.345.jar | bdea6e9d19f35da4858ffcc93210c6207dd590bd |

	Loaded coremods (and transformers): 
BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  me.superckl.biometweakercore.BiomeTweakerASMTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by C0LiSii0N** [comment]
Well, working when I remove the second argument in the createBiome section, seems broken :/

**Comment by superckl** [comment]
Please try downgrading to the latest recommended Forge version.

**Comment by pennyvise1** [comment]
Which forge version? I've tried this on 2655, 2669 and 2673.  I only get this error when I try to run a server, not when creating a single player world.

**Comment by C0LiSii0N** [comment]
I use the latest forge version, I just changed the way I register my biome, I don't put a biome to copy directly with second argument, I just made a list of things to inherit and a list of things to set and now it's working fine, as I said in issue #186 some properties can't be inherited so maybe that's why I can't copy a biome with the second argument.
I attached my scripts, may help some people
[scripts.zip](https://github.com/superckl/BiomeTweaker/files/1949871/scripts.zip)

**Comment by superckl** [comment]
No, this is an actual bug with how I go about copying the biome's name. I just haven't had time to fix it.

**Comment by C0LiSii0N** [comment]
Ok! Well as it's now working fine for me I don't mind, at least now you can redirect people to this issue if someone else have this issue as a temporary fix ^^
