### ISSUE TITLE
[1.19.2-4.1.3] `/biometweaker output` doesn't generate biomes

### ISSUE THREAD

**Issue by thimblebird** [superckl/BiomeTweaker#289]
pretty much like https://github.com/superckl/BiomeTweaker/issues/280, except I have no clue what's going on:

```
[26Nov2022 15:22:01.460] [Server thread/INFO] [biometweaker/]: Generating Biome status report...
[26Nov2022 15:22:01.461] [Server thread/ERROR] [biometweaker/]: Caught an exception while generating Biome status report!
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because the return value of "me.superckl.biometweaker.util.RegistryNameHelper.getRegistryName(net.minecraft.world.level.biome.Biome)" is null
	at me.superckl.biometweaker.Output.lambda$generateOutputFiles$3(Output.java:56) ~[biometweaker-1.19.2-4.1.3.jar%23169!/:1.19.2-4.1.3]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at me.superckl.biometweaker.Output.genOutput(Output.java:104) ~[biometweaker-1.19.2-4.1.3.jar%23169!/:1.19.2-4.1.3]
	at me.superckl.biometweaker.Output.generateOutputFiles(Output.java:54) ~[biometweaker-1.19.2-4.1.3.jar%23169!/:1.19.2-4.1.3]
	at me.superckl.biometweaker.server.command.CommandOutput.output(CommandOutput.java:14) ~[biometweaker-1.19.2-4.1.3.jar%23169!/:1.19.2-4.1.3]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar%23119!/:?]
	at net.minecraft.commands.Commands.m_242674_(Commands.java:240) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_242600_(ServerGamePacketListenerImpl.java:1239) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$12(ServerGamePacketListenerImpl.java:1217) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23336!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[26Nov2022 15:22:01.463] [Server thread/INFO] [biometweaker/]: Generating Entity status report...
[26Nov2022 15:22:01.710] [Server thread/INFO] [biometweaker/]: Generating Dimension status report...
[26Nov2022 15:22:01.818] [Server thread/INFO] [biometweaker/]: Generating Placed Feature status report...
[26Nov2022 15:22:03.196] [Server thread/INFO] [biometweaker/]: Generating Configured Feature status report...
[26Nov2022 15:22:04.419] [Server thread/INFO] [biometweaker/]: Generating Configured Carver status report...
```

[latest.log](https://github.com/superckl/BiomeTweaker/files/10096432/latest.log)

**Comment by thimblebird** [comment]
fixed in 4.1.4
