### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by rihlsul** [superckl/BiomeTweaker#33]
Heya!

Since Biomes o Plenty can't shut off vanilla biomes, I've been tinkering with BiomeTweaker trying to make a world of lush looking oceans with scattered islands.  I've updated to the 129 build you made a few days ago to see if the registerGenBiomeRep command helps me.

My script below is not the intended end goal, but even this simple one crashes:

```
allNotOcean = forAllBiomesExcept(0,94-98)
allNotOcean.registerGenBiomeRep(0)
allNotOcean.set("height", -1)
allNotOcean.set("heightVariation", 0.1)
```

(94-98 are BoP Ocean-type biomes like Coral Reef and a few tropic/volcano biomes for island generation)

The crash is
```
[12:20:36] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.terraingen.BiomeEvent$CreateDecorator@64cde9a5:
java.lang.NoSuchFieldError: biomeID
	at me.superckl.biometweaker.common.handler.BiomeEventHandler.onCreateBiomeDecorator(BiomeEventHandler.java:205) ~[BiomeEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_27_BiomeEventHandler_onCreateBiomeDecorator_CreateDecorator.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.minecraftforge.event.terraingen.DeferredBiomeDecorator.fireCreateEventAndReplace(DeferredBiomeDecorator.java:43) [DeferredBiomeDecorator.class:?]
	at net.minecraftforge.common.BiomeDictionary.registerAllBiomesAndGenerateEvents(BiomeDictionary.java:300) [BiomeDictionary.class:?]
```

Thinking it was something I've done, I went ahead and spun up a clean 1.7.10 with Forge 10.13.4.1448.  I added only 3 mods, Biomes o Plenty 2.1.0.1004, BiomeTweaker 129dev, and JourneyMap 5.0.1.  I setup no scripts at all. The crash happens so early, it doesn't even generate the default BiomeTweaker config files.

Still same crashing.  Full log in the pastebin:
http://pastebin.com/YHBhuUJJ

I spun up a new clean 1.7.10 with Forge 10.13.4.1448 and added only BiomeTweaker.  Same crash.

Thanks for the help!

Let me know if there's anything else you need.  I can zip up the whole shebang and dropbox it if that helps testing (~7MB).

**Comment by nanakisan** [comment]
You're using the dev version of BiomeTweaker which is unobfuscated. you will want this version jenkins.superckl.me/job/BiomeTweaker/129/artifact/build/libs/BiomeTweaker-1.7.10-1.2.129.jar

**Comment by superckl** [comment]
What @nanakisan said.

**Comment by rihlsul** [comment]
(facepalm) Thank you for the speedy fix (by which I mean pointing out what should have been obvious).
