### ISSUE TITLE
Unable to set air for water.

### ISSUE THREAD

**Issue by keybounce** [superckl/BiomeTweaker#4]
I am getting large numbers of these:
[16:06:59] [Client thread/ERROR] [BiomeTweaker]: Failed to retrieve inserted fields!
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at me.superckl.biometweaker.util.BiomeHelper.fillJsonObject(BiomeHelper.java:41)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:73)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:06:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
...

This happens during early startup, and was caused by
allBiomes.set("liquidFillerBlock", minecraft:air)

**Comment by superckl** [comment]
You need to wrap the block name in quotes:

    allBiomes.set("liquidFillerBlock", "minecraft:air")

**Comment by keybounce** [comment]
Ahh ...

For what it's worth, it worked without the quotes. I don't know if that's because it just wound up with "null", that happens to be air or not. Lets see if the error messages go away

**Comment by keybounce** [comment]
Yep, errors are gone. Thank you.

**Comment by superckl** [comment]
Yeah, no problem.

The parser would usually catch such a mistake, but it can't for the 'set' command since the second argument depends on the first, e.g. 'grassColor' takes an integer, while 'fillerBlock' requires a String.
