### ISSUE TITLE
Set top block problems

### ISSUE THREAD

**Issue by Eruraion** [superckl/BiomeTweaker#41]
So, ive been trying to change the top block (and under block) and getting no where with it.

world = forAllBiomes()

world.set("topBlock", "Salvagecore:Dirt")
world.set("fillerBlock", "Salvagecore:Dirt")
world.set("actualFillerBlock", "Salvagecore:Stone")

This results in nothing changing. nothing. So i tried a different approch to it.

world.registerGenBlockRep("minecraft:stone", "Salvagecore:Stone")
world.registerGenBlockRep("minecraft:dirt", "Salvagecore:Dirt")
world.registerGenBlockRep("minecraft:grass", "Salvagecore:Dirt")

Now all the stone has been switched, but no grass or dirt spawns. nothing, just a stone world.

So just to test to see if it was my mod causing a problem

world.registerGenBlockRep("minecraft:stone", "Salvagecore:Dirt")
world.registerGenBlockRep("minecraft:dirt", "Salvagecore:Stone")
world.registerGenBlockRep("minecraft:grass", "Salvagecore:Stone")

Nope, now all the stone is dirt, but still no top layer(s)...

So just to try it out:

world.registerGenBlockRep("minecraft:grass", "minecraft:dirt")

nope, now just spawns grass.

so... what now?

**Comment by superckl** [comment]
What build are you using? And a full client log, please.

**Comment by Eruraion** [comment]
im using 1.2.128

I had this problem a week ago, i only just found this to report it. ill get the client logs tomorow. its way to late now.

also, was not expecting such a quick response.

**Comment by superckl** [comment]
My guess is you're misunderstanding what "actualFillerBlock" actually does. It's simply a flag to let the biome generators know what they should be placing the top and filler blocks over. They check for stone normally, but if you change it to dirt, they won't find stone and thus won't place their top and filler blocks. Try something like this:

```
world.set("topBlock", "Salvagecore:Dirt")
world.set("fillerBlock", "Salvagecore:Dirt")
world.registerGenBlockRep("minecraft:stone", "Salvagecore:Stone")
world.set("actualFillerBlock", "Salvagecore:Stone")
```

**Comment by Eruraion** [comment]
Alright, so i changed some configs and got this:
wasteland = forBiomes(1, 128, 129, 4, 132, 27, 155, 28, 156, 35, 163, 2, 130, 7, 16, 0, 24, 13, 19, 18, 33, 21, 149, 23, 151, 37, 165, 36, 38, 39, 164, 166, 167)
notwasteland = forAllBiomesExcept(1, 128, 129, 4, 132, 27, 155, 28, 156, 35, 163, 2, 130, 7, 16, 0, 24, 13, 19, 18, 33, 21, 149, 23, 151, 37, 165, 36, 38, 39, 164, 166, 167)
plains = forBiomes(1, 128, 129, 4, 132, 27, 155, 28, 156, 35, 163) 
desert = forBiomes(2, 130)
ocean = forBiomes(7, 16, 0, 24)
preplace = forBiomes(13, 19, 18, 33)
dreplace = forBiomes(21, 149, 23, 151, 37, 165, 36, 38, 39, 164, 166, 167)
spawn = forBiomes(2, 1)
nospawn = forAllBiomesExcept(2, 1)

notwasteland.remove()
preplace.registerGenBiomeRep(1)
dreplace.registerGenBiomeRep(2)

wasteland.set("actualFillerBlock", "Falloutsalvage:Stone")
wasteland.registerGenBlockRep("minecraft:stone", "Falloutsalvage:Stone")

plains.set("topBlock", "Falloutsalvage:Dirt")
desert.set("topBlock", "Falloutsalvage:Sand")
ocean.set("topBlock", "Falloutsalvage:Dirt")

plains.set("fillerBlock", "Falloutsalvage:Dirt")
desert.set("fillerBlock", "Falloutsalvage:Dirt"
ocean.set("fillerBlock", "Falloutsalvage:Dirt")

and it gave me this:

---- Minecraft Crash Report ----
// Don't do that.

Time: 10/17/15 10:42 AM
Description: Exception preparing structure feature

java.lang.ArithmeticException: / by zero
	at net.minecraft.world.gen.layer.GenLayer.func_75902_a(GenLayer.java:134)
	at net.minecraft.world.gen.layer.GenLayerBiome.getWeightedBiomeEntry(GenLayerBiome.java:132)
	at net.minecraft.world.gen.layer.GenLayerBiome.func_75904_a(GenLayerBiome.java:116)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerBiomeEdge.func_75904_a(SourceFile:14)
	at net.minecraft.world.gen.layer.GenLayerHills.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerRareBiome.func_75904_a(SourceFile:13)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerAddIsland.func_75904_a(SourceFile:16)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerShore.func_75904_a(SourceFile:13)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerSmooth.func_75904_a(SourceFile:15)
	at net.minecraft.world.gen.layer.GenLayerRiverMix.func_75904_a(SourceFile:24)
	at net.minecraft.world.biome.WorldChunkManager.func_150795_a(WorldChunkManager.java:221)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_75047_a(MapGenStronghold.java:95)
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:222)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.gen.layer.GenLayer.func_75902_a(GenLayer.java:134)
	at net.minecraft.world.gen.layer.GenLayerBiome.getWeightedBiomeEntry(GenLayerBiome.java:132)
	at net.minecraft.world.gen.layer.GenLayerBiome.func_75904_a(GenLayerBiome.java:116)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerBiomeEdge.func_75904_a(SourceFile:14)
	at net.minecraft.world.gen.layer.GenLayerHills.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerRareBiome.func_75904_a(SourceFile:13)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerAddIsland.func_75904_a(SourceFile:16)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerShore.func_75904_a(SourceFile:13)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:20)
	at net.minecraft.world.gen.layer.GenLayerSmooth.func_75904_a(SourceFile:15)
	at net.minecraft.world.gen.layer.GenLayerRiverMix.func_75904_a(SourceFile:24)
	at net.minecraft.world.biome.WorldChunkManager.func_150795_a(WorldChunkManager.java:221)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_75047_a(MapGenStronghold.java:95)

-- Feature being prepared --
Details:
	Is feature chunk: ~~ERROR~~ ArithmeticException: / by zero
	Chunk location: -12,-2
	Chunk pos hash: -4294967308
	Structure type: net.minecraft.world.gen.structure.MapGenStronghold
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:222)

-- Chunk to be generated --
Details:
	Location: -4,6
	Position hash: 30064771068
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-52,64,108), Chunk: (at 12,4,12 in -4,6; contains blocks -64,0,96 to -49,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.world.World.func_147474_b(World.java:329)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: 6968324108465944195
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.World.<init>(World.java:260)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1814790840 bytes (1730 MB) / 2150354944 bytes (2050 MB) up to 3006529536 bytes (2867 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 25, tcache: 74, allocated: 4, tallocated: 19
	FML: MCP v9.05 FML v7.10.140.1401 Minecraft Forge 10.13.3.1401 23 mods loaded, 22 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{7.10.140.1401} [Forge Mod Loader] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{10.13.3.1401} [Minecraft Forge] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	bettersleepingcore{1.0} [Better Sleeping Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	bettersleeping{1.7.10-0.8.22} [Better Sleeping] (BetterSleeping-1.7.10-0.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	betterstorage{0.11.1.121} [BetterStorage] (BetterStorage-1.7.10-0.11.1.121.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BiomeTweaker{1.2.128} [BiomeTweaker] (BiomeTweaker-1.7.10-1.2.128.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	cannibalism{1.1.1} [Cannibalism] (Cannibalism-1.1.1-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	enviromine{1.3.118} [EnviroMine] (EnviroMine-1.3.118.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Falloutsalvage{1.0.3} [Falloutsalvage] (Falloutsalvage.zip.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FastCraft{1.19} [FastCraft] (fastcraft-1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	glass_shards{1.3.2} [Glass Shards] (glass_shards_mc1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	infernalskycolor{0.8} [Infernal Sky Color] (InfernalSkyColor-0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Progression{0.4.1} [Progression] (Progression-1.7.10-0.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	shouldersurfing{1.0} [ShoulderSurfing] (shouldersurfing-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	simplefluidtanks{1.7.10-1.2.0.5} [Simple Fluid Tanks] (simplefluidtanks-1.7.10-1.2.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BiomeTweakerCore{1.2.128} [BiomeTweaker Core] (minecraft.jar) Unloaded->Disabled
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by superckl** [comment]
Full client log please. BiomeTweaker is telling you why it's crashing. Just search the log for "BiomeTweaker".

**Comment by superckl** [comment]
I guess I should elaborate a bit more. There's something called the 'BiomeManager' in Forge. The BiomeManager has four different types that biomes can be registered to. Minecraft asks the BiomeManager for all biomes of a certain type, and chooses one. However, you remove all the biomes of that type, Minecraft crashes with the report you are seeing. See #40 for a solution.

Also, you're using version 1.2.128, yet are trying to use the 'registerGenBiomeRep' command. That was added in version 1.2.129. If you want to use that command, you'll have to grab a development build. Here's the latest one:
http://jenkins.superckl.me/job/BiomeTweaker/152/

**Comment by Eruraion** [comment]
So, created a new world for the client logs. did not change anything... and it worked...

[19:01:17] [Client thread/INFO] [BiomeTweaker]: Found 8 tweaks to apply for stage FINISHED_LOAD. Applying...
[19:01:18] [Client thread/WARN] [BiomeTweaker]: Viable generation biomes for type ICY is empty! This will cause Vanilla generation to crash! You've been warned!
[19:01:18] [Client thread/INFO] [BiomeTweaker]: Error applying tweaks. Biome ID 128 does not correspond to a biome! Check the output files for the correct ID!
[19:01:18] [Client thread/INFO] [BiomeTweaker]: Error applying tweaks. Biome ID 128 does not correspond to a biome! Check the output files for the correct ID!
[19:01:18] [Client thread/INFO] [BiomeTweaker]: Error applying tweaks. Biome ID 128 does not correspond to a biome! Check the output files for the correct ID!
[19:01:18] [Client thread/INFO] [BiomeTweaker]: Error applying tweaks. Biome ID 128 does not correspond to a biome! Check the output files for the correct ID!
[19:01:18] [Client thread/INFO] [BiomeTweaker]: Generating biome status report...

**Comment by Eruraion** [comment]
Stone was there, dirt was there, biomes all changed. flew around... worked.

**Comment by superckl** [comment]
It'll crash when it attempts to generate an ICY biome. Did you see any snow biomes?

**Comment by Eruraion** [comment]
ya, i saw that. i added ice plains to the config

**Comment by superckl** [comment]
If that's it, I'm going to close the issue. You can keep commenting here if you have more questions.

**Comment by Eruraion** [comment]
Actually, i do have a question. the under layer of sand is being a bit stubborn. the very top layer of sand gets replaced. but all the sand under the first block dosent. 

wasteland.registerGenBlockRep("minecraft:sand", "Falloutsalvage:Sand") does nothing to help.

and desert.set("fillerBlock", "Falloutsalvage:Sand") also does nothing.

**Comment by superckl** [comment]
Not sure. I successfully replaced the fillerBlock with glass in test world. Can I get a log?

http://i.imgur.com/3KAqcb1.png
