### ISSUE TITLE
incompatibility with RTG alpha for 1.8.9

### ISSUE THREAD

**Issue by topisani** [superckl/BiomeTweaker#79]
We are currently developing Realistic Terrain Generation for 1.8.9, but when using biometweaker along with our alpha versions, I crash when trying to enter any world, old or new, default worldtype or RTG's. I am guessing we somehow register our biomes wrong, but maybe you can make sense of it.

```
[11:20:33] [Server thread/ERROR]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: field_76756_M

    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:858) [Loader.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
    at net.minecraft.server.integrated.IntegratedServer.startServer(IntegratedServer.java:126) [IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:508) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.NoSuchFieldError: field_76756_M
    at me.superckl.biometweaker.util.BiomeHelper.setBiomeProperty(BiomeHelper.java:269) ~[BiomeTweaker-1.8.9-2.0.184.jar:?]
    at me.superckl.biometweaker.script.command.ScriptCommandSetBiomeProperty.perform(ScriptCommandSetBiomeProperty.java:30) ~[ScriptCommandSetBiomeProperty.class:?]
    at me.superckl.api.superscript.ScriptCommandManager.applyCommandsFor(ScriptCommandManager.java:56) ~[BiomeTweaker-1.8.9-2.0.184.jar:?]
    at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:165) ~[BiomeTweaker.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forgeSrc-1.8.9-11.15.1.1756.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:745) ~[forgeSrc-1.8.9-11.15.1.1756.jar:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310) ~[forgeSrc-1.8.9-11.15.1.1756.jar:?]
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:532) ~[forgeSrc-1.8.9-11.15.1.1756.jar:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:360) ~[forgeSrc-1.8.9-11.15.1.1756.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:116) ~[forgeSrc-1.8.9-11.15.1.1756.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) ~[GradleStartCommon.class:?]
    at GradleStart.main(GradleStart.java:26) ~[GradleStart.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) ~[AppMain.class:?]
[11:20:33] [Server thread/INFO]: Applying holder lookups
[11:20:33] [Server thread/INFO]: Holder lookups applied
[11:20:33] [Server thread/INFO]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
```

**Comment by topisani** [comment]
sorry this is probably me being a total idiot. closing untill i potentially find out its not
