### ISSUE TITLE
Biometweaker in dev environment

### ISSUE THREAD

**Issue by topisani** [superckl/BiomeTweaker#81]
Hi, we are currently working on updating RTG to 1.8.9, and its mod support depends on biometweaker positioning the biomes. it works fine when i throw it in a mod folder, but inside my dev envvironment (both in the libs and mods folders) it fails to open up any world, new or old.
log:

```
Caught exception from BiomeTweaker
java.lang.NullPointerException
    at me.superckl.biometweaker.BiomeTweaker.generateOutputFiles(BiomeTweaker.java:180) ~[BiomeTweaker.class:?]
    at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:166) ~[BiomeTweaker.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forgeSrc-1.8.9-11.15.1.1756.jar:?]
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
```

**Comment by superckl** [comment]
Need a full log. That error looks like the class transformer is failing to add the fields needed. This will show in the class transformers log if so.

**Comment by superckl** [comment]
Try with latest builds.
