### ISSUE TITLE
Caught an exception from module moduleTransformBiomeGenBaseSubclass

### ISSUE THREAD

**Issue by MrBloodowrth** [superckl/BiomeTweaker#86]
`[13:54:16] [Server thread/ERROR] [BiomeTweakerCore]: Caught an exception from module moduleTransformBiomeGenBaseSubclass
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.RuntimeException: raw = ic2/api/crops/CropCard, obf = ic2/api/crops/CropCard
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at squeek.asmhelper.me.superckl.biometweaker.ASMHelper.doesClassExtend(ASMHelper.java:182)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at me.superckl.biometweaker.core.module.ModuleBiomeGenBaseSubclass.transform(ModuleBiomeGenBaseSubclass.java:28)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at me.superckl.biometweaker.core.BiomeTweakerASMTransformer.transform(BiomeTweakerASMTransformer.java:40)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.ClassLoader.loadClass(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.ClassLoader.loadClass(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at minetweaker.mods.ic2.ClassRegistry.getClasses(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at minetweaker.MineTweakerAPI.registerClassRegistry(MineTweakerAPI.java:259)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at minetweaker.MineTweakerAPI.registerClassRegistry(MineTweakerAPI.java:313)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at minetweaker.mc1710.MineTweakerMod.onPostInit(MineTweakerMod.java:146)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.io.IOException: Class not found
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.objectweb.asm.ClassReader.a(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.objectweb.asm.ClassReader.<init>(Unknown Source)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at squeek.asmhelper.me.superckl.biometweaker.ASMHelper.getClassReaderForClassName(ASMHelper.java:129)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at squeek.asmhelper.me.superckl.biometweaker.ASMHelper.doesClassExtend(ASMHelper.java:178)
[13:54:16] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  ... 45 more
`

This happens at at least three points. While no crash occurs, it does fill ones console log.

**Comment by superckl** [comment]
Yeah... Not really sure what's causing this to happen, but it happens with AE2 cable busses as well. Everything will still function appropriately... I'll look into reducing the spam.

**Comment by MrBloodowrth** [comment]
I do have Ae2 installed, as well as Betterstorage (The first mod I added when this came up).

BetterStorage-1.7.10-0.13.1.127
appliedenergistics2-rv2-stable-10

For reference, I believe you have encountered this before. When I search for that first line, this is what comes up first: https://github.com/superckl/BiomeTweaker/issues/80

May be related, not sure.  Let me know if you need any more info, thanks!

**Comment by Mordenkainen** [comment]
This is the same as #80...

The fix is to update ASMHelper. Squeek put a fix for this issue in on Dec 20th: https://github.com/squeek502/ASMHelper/commit/9df26a5fe01ab2f82e506957e8a52af6e73a2e5f

**Comment by superckl** [comment]
Thank you @Mordenkainen 

This is fixed in 1.8+ which use ASMHelper at commit squeek502/ASMHelper@05c5e8d (more recent than the relevant change). I will be updating the ASMHelper dependency to even more recent commit soon.

Since the 1.7.10 branch is no longer under development, this is a non-issue.
