### ISSUE TITLE
BiomeTweaker-1.9 2.1.199 prevents help from being used

### ISSUE THREAD

**Issue by kreezxil** [superckl/BiomeTweaker#88]
With this mod installed my server which is running the Forge 1.9 build 1904, while not crashing, won't let players use the help system. The only error is in the console.

```
[19:19:08] [Server thread/WARN]: Couldn't process command: 'help'
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at me.superckl.biometweaker.server.command.CommandInfo.func_71518_a(CommandInfo.java:41) ~[CommandInfo.class:?]
        at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:104) ~[ak.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:102) [j.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:81) [j.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:422) [la.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [la.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
        ... 9 more
Caused by: java.lang.NullPointerException
```

I removed all of my mods and only have your mod and biomes-oplenty-1.9-4.0.2.2018 installed.

**Comment by superckl** [comment]
Thanks for reporting this! Build with fix is released.

http://minecraft.curseforge.com/projects/biometweaker/files/2300569
