### ISSUE TITLE
New crash on world starts

### ISSUE THREAD

**Issue by Zygus42** [superckl/BiomeTweaker#93]
Probably due to Realistic Terrain Generation and Biomes O Plenty updating, have started getting this crash on world gen:

[21:34:01] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from AVAILABLE to SERVER_ABOUT_TO_START. Loading cannot continue
[21:34:01] [Server thread/ERROR] [FML]: 
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAA mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAA FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2095.jar) 
    UCHIJAA Forge{12.18.1.2095} [Minecraft Forge](forge-1.10.2-12.18.1.2095.jar) 
    UCHIJAA Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAA Botania{r1.9-328} [Botania](Botania r1.9-328.jar) 
    UCHIJAA AkashicTome{1.0-4} [Akashic Tome](AkashicTome-1.0-4.jar) 
    UCHIJAA ArmorDamageRecalc{1.2} [Armor Damage Recalc](ArmorDamageRecalc-1.2 ALPHA for 1.10.2.jar) 
    UCHIJAA basemetals{2.4.0} [Base Metals](BaseMetals_1.10.2-2.4.0.11.jar) 
    UCHIJAA golems{6.02} [Extra Golems](ExtraGolems[1.10.2]-6.02.jar) 
    UCHIJAA golems_metal{6.02.1} [Base Metal Golems](BaseMetalGolems[1.10]-6.02.1.jar) 
    UCHIJAA hud{1.3.8} [Better HUD](Better HUD by NukeDuck [1.9.4][1.3.8].jar) 
    UCHIJEE BiomeTweaker{2.1.225} [BiomeTweaker](BiomeTweaker-1.10.2-2.1.225.jar) 
    UCHIJAA BiomesOPlenty{5.0.0.2086} [Biomes O' Plenty](BiomesOPlenty-1.10.2-5.0.0.2086-universal.jar) 
    UCHIJAA botanicaladdons{GRADLE:VERSION.GRADLE:BUILD} [Natural Pledge](Botania - NaturalPledge-r1.5.jar) 
    UCHIJAA chickens{1.9.4-3.0} [Chickens](chickens-1.9.4-3.0.jar) 
    UCHIJAA chisel{MC1.9.4-0.0.6.48} [Chisel](Chisel-MC1.9.4-0.0.6.48.jar) 
    UCHIJAA combathelp{1.0.3} [Combat Help](combathelp-1.9.4-1.0.3.jar) 
    UCHIJAA coralreef{1.0} [Coral Reef](CoralReef-1.2.jar) 
    UCHIJAA MineTweaker3{3.0.12} [MineTweaker 3](CraftTweaker-1.10.2-3.0.12.jar) 
    UCHIJAA modtweaker{2.0.4} [Mod Tweaker](CraftTweaker-ModTweaker2-1.10.2-2.0.4.jar) 
    UCHIJAA mantle{1.10.2-1.0.0.jenkins170} [Mantle](TConstruct-Mantle-1.10.2-1.0.0.jar) 
    UCHIJAA tconstruct{1.10.2-2.5.3.jenkins387} [Tinkers' Construct](TConstruct-1.10.2-2.5.3.jar) 
    UCHIJAA immersiveengineering{0.10-44} [Immersive Engineering](ImmersiveEngineering-0.10-44.jar) 
    UCHIJAA JEI{3.12.5.303} [Just Enough Items](jei_1.10.2-3.12.5.303.jar) 
    UCHIJAA guideapi{@VERSION@} [Guide-API](Silent Gems - Guide-API-1.10.2-2.0.2-45.jar) 
    UCHIJAA crossroads{1.10.2-1.1.4} [Crossroads](crossroads-1.10.2-1.1.4.jar) 
    UCHIJAA cyberware{beta-0.2.3} [Cyberware](cyberware-1.9.4-1.10.2-beta-0.2.3.jar) 
    UCHIJAA disenchanter{1.4} [Disenchanter](disenchanter-[1.9.4]1.4.jar) 
    UCHIJAA dooglamoocitiesmod{1.10.2-1.1} [Dooglamoo Cities Mod](dooglamoocitiesmod-1.10.2-1.1.jar) 
    UCHIJAA DragonMounts{r46-1.10.2} [Dragon Mounts](DragonMounts-r46-1.10.2.jar) 
    UCHIJAA lootablebodies{2.2.0} [DrCyano's Lootable Bodies](DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
    UCHIJAA ea{v2.4.7a-mc1.10.2} [Ebon Arts](EbonArts-v2.4.7a-mc1.10.2.jar) 
    UCHIJAA EnderBags{2.0.1} [EnderBags](EnderBags-1.9.4-2.0.0.jar) 
    UCHIJAA valkyrielib{1.10.2-0.10.4} [Valkyrie Lib](environmentaltech-valkyrielib-1.10.2-0.10.4b.jar) 
    UCHIJAA environmentaltech{1.10.2-0.10.4b} [Environmental Tech](environmentaltech-1.10.2-0.10.4b.jar) 
    UCHIJAA expandablebackpack{1.1} [Expandable Backpacks](expandableBackpacks1.1.9-1.10.2.jar) 
    UCHIJAA extraalchemy{0.3.0.2-release} [Extra Alchemy](extraalchemy-0.3.0.2-release.jar) 
    UCHIJAA flatcoloredblocks{mc1.10-v4.2} [Flat Colored Blocks](flatcoloredblocks-mc1.10-v4.2.jar) 
    UCHIJAA flowercraftmod{6.01} [Flowercraft](Flowercraftmod v6.01 - MC1.10.2 Forge.jar) 
    UCHIJAA PreFoliage{0.9.0 Beta} [PreFoliage](FoliageModTest.jar) 
    UCHIJAA forestry{5.2.14.263} [Forestry](forestry_1.10.2-5.2.14.263.jar) 
    UCHIJAA glasscraftmod{1.0} [Glasscraft](Glasscraftmod v1.0 - MC1.10.2 Forge.jar) 
    UCHIJAA helpertools{v3.0c} [HelperTools](HelperTools-1.10.2-v3.0c.jar) 
    UCHIJAA JEFB{1.0.4} [Just Enough Forestry Bees](jefb_1.10.2-1.0.4.jar) 
    UCHIJAA journeymap{1.10.2-5.3.0b1} [JourneyMap](journeymap-1.10.2-5.3.0b1-unlimited.jar) 
    UCHIJAA lightningcraft{2.5.2} [LightningCraft](lightningcraft-2.5.2-[1.10.2].jar) 
    UCHIJAA lit{@VERSION@} [Little Insignificant Things](LittleInsignificantThings-1.10-3.0.3.jar) 
    UCHIJAA mcmultipart{1.2.0_74} [MCMultiPart](MCMultiPart-experimental-1.2.0_74-universal.jar) 
    UCHIJAA Mekanism{9.2.0} [Mekanism](Mekanism-1.10.2-9.2.0.292.jar) 
    UCHIJAA MekanismGenerators{9.2.0} [MekanismGenerators](MekanismGenerators-1.10.2-9.2.0.292.jar) 
    UCHIJAA MekanismTools{9.2.0} [MekanismTools](MekanismTools-1.10.2-9.2.0.292.jar) 
    UCHIJAA mikedongles{0.3.1} [Mike Dongles](MikeDongles-0.3.1-MC[1.9.4-1.10-1.10.2].jar) 
    UCHIJAA moreanvils{6.0.2.11} [More Anvils](MoreAnvils-Forge-6.0.2.11.jar) 
    UCHIJAA morebees{1.10.2-1.1.3} [More Bees](morebees-1.10.2-1.1.3.jar) 
    UCHIJAA moreoverlays{1.8} [MoreOverlays](moreoverlays-1.8-mc1.10.2.jar) 
    UCHIJAA moreshears{1.0.0} [More Shears](moreshears-1.10.2-1.0.1-release.jar) 
    UCHIJAA mysticalagriculture{1.2.4} [Mystical Agriculture](mysticalagriculture-1.2.4.jar) 
    UCHIJAA natura{1.10.2-4.0.0.81} [Natura](natura-1.10.2-4.0.0.81.jar) 
    UCHIJAA netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UCHIJAA recipehandler{0.5} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.5%281.10.2%29.jar) 
    UCHIJAA fodc{1.9.1} [Ore Dictionary Converter](OreDictionaryConverter-1.9.1.jar) 
    UCHIJAA orespawn{1.1.0} [Ore Spawn](OreSpawn_1.10.2-1.1.0.jar) 
    UCHIJAA harvestcraft{1.9.4-1.10.2e} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2e.jar) 
    UCHIJAA placemod{3.8} [Placemod](placemod-3.8-1.10.2.jar) 
    UCHIJAA planttech{1.7.3} [Planttech](planttech-1.7.3.jar) 
    UCHIJAA Psi{r1.0-40} [Psi](Psi-r1.0-40.jar) 
    UCHIJAA psionup{GRADLE:VERSION.GRADLE:BUILD} [PSIonic Upgrades](PSIonicUpgrades-r1.14.jar) 
    UCHIJAA Quark{r1.0-56} [Quark](Quark-r1.0-56.jar) 
    UCHIJAA AutoRegLib{1.0-2} [AutoRegLib](Quark+Psi+Akashic - AutoRegLib-1.0-2.jar) 
    UCHIJAA railcraft{10.0.0-beta-2} [Railcraft](Railcraft_1.10.2-10.0.0-beta-2.jar) 
    UCHIJAA randomthings{3.7.6} [Random Things](RandomThings-MC1.10.2-3.7.6.jar) 
    UCHIJAA redstonepaste{1.7.4} [Redstone Paste](redstonepaste-mc1.9.4-1.7.4.jar) 
    UCHIJAA reptilemod{3.5.2} [Reptile Mod](reptilemod-1.10.2-3.5.2-58.jar) 
    UCHIJAA rftools{5.50} [RFTools](rftools-1.10-5.50.jar) 
    UCHIJAA Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJAA roots{0.204} [Roots](roots-1.10.2-0.204.0.jar) 
    UCHIJAA RTG{1.10.2} [Realistic Terrain Generation](RTG-1.10.2-4.1.1.2.jar) 
    UCHIJAA safejoin{1.3} [SafeJoin](SaveJoin-mc1.10.2-1.3.jar) 
    UCHIJAA LunatriusCore{1.1.2.36} [LunatriusCore](Schematica - LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
    UCHIJAA Schematica{1.7.8.152} [Schematica](Schematica-1.10.2-1.7.8.152-universal.jar) 
    UCHIJAA cxlibrary{1.2.2} [CXLibrary](sensorcraft - cxlibrary-1.10.2-1.2.2.jar) 
    UCHIJAA sensorcraft{0.4.0} [SensorCraft](sensorcraft-1.10-0.4.0.jar) 
    UCHIJAA shearmadness{1.10.2} [Shear Madness](shearmadness-1.10.2-1.2.1.jar) 
    UCHIJAA Signals{1.0} [Signals](Signals-1.10.2-0.4.3-universal.jar) 
    UCHIJAA signpic{2.1.5} [SignPicture](SignPicture-1.10.2-2.1.5-universal.jar) 
    UCHIJAA SilentLib{1.0.12} [Silent Lib](SilentLib-1.9.4-1.0.12-20.jar) 
    UCHIJAA WIT{1.0.20} [WIT](WIT-1.9.4-1.0.20-38.jar) 
    UCHIJAA SilentGems{2.0.33} [Silent's Gems](SilentsGems-1.10.2-2.0.33-73.jar) 
    UCHIJAA gemulation{1.10-4.0.0} [Gemulation](SilentGems & LIT - Gemulation-1.10-4.0.0.jar) 
    UCHIJAA Chameleon{1.10-2.1.7} [Chameleon](StorageDrawers - Chameleon-1.10-2.1.7.jar) 
    UCHIJAA StorageDrawers{1.10.2-3.2.7} [Storage Drawers](StorageDrawers-1.10.2-3.2.7.jar) 
    UCHIJAA Farseek{1.9.4} [Farseek](Streams - Farseek-1.9.4-1.1.jar) 
    UCHIJAA Streams{1.9.4} [Streams](Streams-1.9.4-0.2.1.jar) 
    UCHIJAA thutcore{3.5.1} [ThutCore](thutcore-1.9.4-3.5.1.jar) 
    UCHIJAA thuttech{4.0.5} [Thut's Tech](thuttech-4.0.5.jar) 
    UCHIJAA trashslot{6.3.6} [TrashSlot](TrashSlot_1.10.2-6.3.6.jar) 
    UCHIJAA UndergroundOcean{${version}} [Underground Ocean](UndergroundOcean-1.1.0_develop_a69b2f0_alpha.jar) 
    UCHIJAA vc{v2.0.0a-mc1.10.2} [ViesCraft](ViesCraft-2.0.0a-mc1.10.2.jar) 
    UCHIJAA villagebox{0.5.0} [Village Box](villagebox-1.10.2-0.5.0.jar) 
    UCHIJAA tammodized{0.2.2} [TamModized](VoidCraft-TamModized-1.10.2-0.2.2.jar) 
    UCHIJAA voidcraft{0.9.5} [VoidCraft](VoidCraft-1.10.2-0.9.5.jar) 
    UD  BiomeTweakerCore{2.1.225} [BiomeTweaker Core](minecraft.jar) 
[21:34:01] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[21:34:01] [Server thread/ERROR] [FML]: Caught exception from BiomeTweaker
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
    at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_101]
    at java.io.File.createNewFile(Unknown Source) ~[?:1.8.0_101]
    at me.superckl.biometweaker.BiomeTweaker.generateOutputFiles(BiomeTweaker.java:238) ~[BiomeTweaker.class:?]
    at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:211) ~[BiomeTweaker.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597) ~[forge-1.10.2-12.18.1.2095.jar:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:798) ~[Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) ~[FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) ~[bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) ~[bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) ~[1.10.2.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
[21:34:01] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect

```
at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186) ~[LoadController.class:?]
at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:911) [Loader.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:119) [bzl.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
    at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_101]
    at java.io.File.createNewFile(Unknown Source) ~[?:1.8.0_101]
    at me.superckl.biometweaker.BiomeTweaker.generateOutputFiles(BiomeTweaker.java:238) ~[BiomeTweaker.class:?]
    at me.superckl.biometweaker.BiomeTweaker.onLoadComplete(BiomeTweaker.java:211) ~[BiomeTweaker.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597) ~[forge-1.10.2-12.18.1.2095.jar:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:798) ~[Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) ~[FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) ~[bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) ~[bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) ~[1.10.2.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
[21:34:01] [Server thread/INFO]: Stopping server
[21:34:01] [Server thread/INFO]: Saving players
[21:34:01] [Server thread/INFO]: Saving worlds

**Comment by Zygus42** [comment]
Actually, on further testing is being caused by the addition of Voidcraft to the mod mix.  Will report it there instead.

**Comment by superckl** [comment]
Accounting for this on my side.

**Comment by superckl** [comment]
https://minecraft.curseforge.com/projects/biometweaker/files/2334753
